### PR TITLE
Added trade and global chat filtering (specifically for challenges)

### PR DESCRIPTION
**Pull request by DetectiveSquirrel**
needs PoEWhisperNotifier.exe XML Configuration file to work
Screenshot: http://puu.sh/uZTE3/cac0e6eaa8.png

### CODE REVIEW

**Comment by Kapps** [comment]
Thanks for the pull, I saw your thread and think it's a nice addition. I'll have to take a closer look later though when not at work.

**Comment by krab** [comment]
Need a fix when searching string ends on | program starts notify about every single message. For exapmle `trove|`

**Comment by krab** [comment]
And yeah Kapps probably ignores your pull request because you changed all indents in every single file/line 🤕 

`+7,900 −7,088 `

**Comment by Kapps** [comment]
Sorry, I should have been replying to this earlier, I just held off since I noticed changes still occurring and because I have to figure out how to actually merge things properly given the amount of changes and things like spacing changes messing up diffs (the whole 8,000 changes thing). It's pretty silly that Github's web interface doesn't handle this properly, but the git command itself does so that's not a huge deal.

I like the changes for filtering and the colours, but I'm concerned about things like the individual notification settings. There's already too many settings and I've been trying to get rid of some (or at least remove UI support and make it config editable only for the advanced users) because it's just an overload of options when people open the program for the first time and try to set things up. In the future, I'll likely even remove things like the client.txt path and just infer it from the copy of PoE you have open (this is also helpful when there's a beta client and such). 

I definitely appreciate all the work done on this and I like the changes. I'll definitely be merging the majority of them, but there were a couple of things I was looking at that I'll need to test more (things like high DPI support with the UI changes) and figure out how to actually merge things properly.

Also, I think the issue you're mentioning makes sense. Assuming it's regex, you should be able to escape it by using trove\|. I'll take a look though after merging (maybe something like detecting if the regex matches N randomly generated strings and warning if it does on all of them, or warning if there's an oddity like the above).

**Comment by DetectiveSquirrel** [comment]
its not regex its just split by | so dont add it on to the end

**Comment by Kapps** [comment]
Okay, sorry about the delay with this. I'm going to merge this into a separate branch, then cherrypick most of the features from it bar a few mentioned above and manually merge them back into the master branch, then hopefully push master and that will work! It will be a bit trickier with GUI designer code and high DPI support, but working on it at the moment.

**Comment by Kapps** [comment]
Done! I refactored things into a dialog to configure settings for individual notification types. I didn't include the individual sound features, but I've added in your colours, colours per message, filtering specific message types like global or trade, and all messages are now logged.

Thanks for your work on this, and sorry that it took so long to get it in.

**Pull request merged**
